package com.ttn.nexuscart.enums;

public enum OrderStatus {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_REJECTED,
    ORDER_SHIPPED,
    DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    PICK_UP_INITIATED,
    PICK_UP_COMPLETED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    CANCELLED,
    CLOSED
}
